# Special Keywords

## Keys (`from` column)

The `from` column of the dictionary will contain the keys that you want to match
in your current data set. These are expected to match exactly with the exception
of three reserved keywords that start with a full stop:

 - `.regex [pattern]`: will replace anything matching [pattern]. This is executed
before any other replacements are made. The [pattern] should be an unquoted,
valid, PERL-flavored regular expression. Any whitespace padding the regular
expression is discarded.
 - `.missing`: replaces any missing values\*
 - `.default`: replaces ALL values that are not defined in the dictionary and 
are not missing.

> \* Any `NA` values in the keys will be interpreted as "NA" because it's a
> common mistake to import the value "NA" to missing in R. If you intend for
> `NA` to indicate missing data, replace it with:
> `dictionary[[1]][is.na(dictionary[[1]]] <- ".missing"`

## Values (`to` column)

The values will replace their respective keys exactly as they are presented with
one exception. There is currently one recognised keyword that can be placed in
the to column of your dictionary:

 - `.na`: Replace keys with missing data. When used in combination with the
 `.missing` keyword (in column 1), it can allow you to differentiate between
 explicit and implicit missing data.
